plugins {
    id 'net.neoforged.moddev.legacyforge' version '2.0.107' apply false
}

subprojects {
    apply plugin: 'java-library'

    group = 'com.silentvector.architects'
    version = "${mod_version}+${minecraft_version}"

    java {
        toolchain.languageVersion = JavaLanguageVersion.of(17)
        withSourcesJar()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        options.release = 17
    }

    repositories {
        mavenCentral()
        exclusiveContent {
            forRepository { maven { name = 'Modrinth'; url = 'https://api.modrinth.com/maven' } }
            filter { includeGroup 'maven.modrinth' }
        }
        maven { name = 'BlameJared'; url = 'https://maven.blamejared.com/' }
        exclusiveContent {
            forRepository {
                maven {
                    name = 'Sponge'
                    url = 'https://repo.spongepowered.org/repository/maven-public'
                }
            }
            filter { includeGroupAndSubgroups('org.spongepowered') }
        }
    }
}
