plugins {
    id 'net.neoforged.moddev'
}

base {
    archivesName = 'adaptive-functional-storage'
}

// adaptive-functional-storage-0.2.1+1.21.1-neoforge.jar
tasks.named('jar', Jar).configure {
    archiveClassifier = loader
}

tasks.withType(Jar).configureEach {
    from(rootProject.file('LICENSE')) {
        into 'META-INF'
        rename { 'LICENSE_adaptive_functional_storage' }
    }
}

tasks.withType(ProcessResources).configureEach {
    def replacements = [
            minecraft_version      : minecraft_version,
            neoforge_version_range : neoforge_version_range,
            loader_version_range   : loader_version_range,
            functionalstorage_version_range : functionalstorage_version_range,
            mod_version            : project.version
    ]
    inputs.properties replacements
    filesMatching('META-INF/neoforge.mods.toml') { expand replacements }
}

configurations {
    commonJava {
        canBeResolved = true
        canBeConsumed = false
    }
    commonResources {
        canBeResolved = true
        canBeConsumed = false
    }
}

configurations.configureEach {
    exclude group: 'mezz.jei'
}

dependencies {
    compileOnly(project(':common'))
    commonJava project(path: ':common', configuration: 'commonJava')
    commonResources project(path: ':common', configuration: 'commonResources')

    implementation "maven.modrinth:cO40ZIg3:${functionalstorage_modrinth}"
    implementation "com.hrznstudio:titanium:${titanium_version}"
    runtimeOnly "maven.modrinth:U6BUTZ7K:${botanypots_modrinth}"
    runtimeOnly "net.darkhax.bookshelf:bookshelf-neoforge-1.21.1:${bookshelf_version}"
    runtimeOnly "net.darkhax.pricklemc:prickle-neoforge-1.21.1:${prickle_version}"
    runtimeOnly "maven.modrinth:fRiHVvU7:${emi_modrinth}"
    compileOnly "maven.modrinth:fRiHVvU7:${emi_modrinth}"
    runtimeOnly "maven.modrinth:blEO0qto:${generatorgalore_modrinth}"
}

tasks.named('compileJava', JavaCompile).configure {
    dependsOn(configurations.commonJava)
    source(configurations.commonJava)
}

tasks.named('processResources', ProcessResources).configure {
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

tasks.named('sourcesJar', Jar).configure {
    dependsOn(configurations.commonJava)
    from(configurations.commonJava)
    dependsOn(configurations.commonResources)
    from(configurations.commonResources)
}

neoForge {
    version = neoforge_version
    runs {
        client {
            client()
            gameDirectory = project.layout.projectDirectory.dir('run/client')
        }
        server {
            server()
            gameDirectory = project.layout.projectDirectory.dir('run/server')
            programArgument '--nogui'
        }
    }
    mods {
        adaptive_functional_storage {
            sourceSet sourceSets.main
        }
    }
}
